### PR TITLE
add google analytics

### PR DESCRIPTION
**Pull request by leo-step**

### CODE REVIEW

**Comment by nicholaspad** [comment]
good idea to add this early on to track growth!

**Comment by leo-step** [comment]
Can we merge this in?

**Comment by nicholaspad** [comment]
yes you can! in the future, just tag us as reviewers and one of us will review it. once it's approved feel free to merge!

**Review by nicholaspad — APPROVED** [review]

**Comment by leo-step** [comment]
Sounds good! For some reason I can't add reviewers or merge even when its approved.

**Comment by nicholaspad** [comment]
> Sounds good! For some reason I can't add reviewers or merge even when its approved.

sorry about that, i just invited you and Aaliyah as maintainers!

**Pull request merged**
